//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BirthdayLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Birthday
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public System.DateTime Date_Of_Birthday { get; set; }
        public string Remark { get; set; }
        public int User_Id { get; set; }
    
        public virtual User User { get; set; }
    }
}
